#!/usr/bin/perl -w

use strict;

my ($PROJECT, $SCHEME, $ACTION) = @ARGV;

my $buildSettings = qx{xcodebuild -project "$PROJECT" -scheme "$SCHEME" -showBuildSettings};

my @args = ("-project", $PROJECT, "-scheme", $SCHEME, "-configuration", "Release", split(/\s+/, $ACTION), "CODE_SIGNING_REQUIRED=NO", "CODE_SIGN_IDENTITY=", "ENABLE_TESTABILITY=YES");

if ($buildSettings =~ /\bPLATFORM_NAME = iphoneos/i) {
  unshift @args, "-destination", "name=iPhone 6s";
  unshift @args, "-sdk", "iphonesimulator";
}

print "xcodebuild @args\n";
exec("xcodebuild", @args);
